# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 939dad92707f3b05650b994a6b4eac9c0e5cf3db956ea0e4794e6964197be7e65dfa6e10f7115f8f0bc55125da87b2ac4c6c49de2148e817771e79032597c1dd

test:
  secret_key_base: e17a1cfc98104827fe2b30760a652047ae1466c5704bc4963668e4e7d9ffeeaf77ed56dba0ed2aa65137de620371af145e37ccd172c104a2208a2a3f7f1c0a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
